USE students;

#Biology Classes
INSERT INTO class (name, credits)
VALUES
	("Introduction to Biology", 4),
	("Cellular and Molecular Biology", 4),
	("Genetics", 4),
	("Evolutionary Biology", 4),
	("Ecology", 3),
	("Anatomy and Physiology", 3),
	("Microbiology", 4),
	("Immunology", 4),
	("Biochemistry", 4),
	("Plant Biology", 3),
	("Animal Behavior", 3),
	("Developmental Biology", 3),
	("Neurobiology", 3),
	("Biostatistics", 3),
	("Marine Biology", 3),
	("Conservation Biology", 3),
	("Environmental Science", 3),
	("Biotechnology", 3),
	("Genomics", 3),
	("Physiology of Exercise", 3),
	("Ornithology", 4),
	("Entomology", 4),
	("Herpetology", 4),
	("Mammalogy", 4),
	("Botany", 4);

#Chemistry Classes
INSERT INTO class (name, credits)
VALUES
	("Introduction to Chemistry", 4),
	("Organic Chemistry", 4),
	("Analytical Chemistry", 4),
	("Physical Chemistry", 4),
	("Inorganic Chemistry", 4),
	("Chemical Biology", 4),
	("Polymer Chemistry", 4),
	("Quantum Chemistry", 4),
	("Spectroscopy", 4),
	("Materials Chemistry", 4),
	("Environmental Chemistry", 4),
	("Thermodynamics", 3),
	("Electrochemistry", 3),
	("Chemical Kinetics", 3),
	("Molecular Modeling", 4),
	("Nanotechnology", 3),
	("Surface Chemistry", 3),
	("Medicinal Chemistry", 3),
	("Catalysis", 3),
	("Organometallic Chemistry", 3),
	("Photochemistry", 3),
	("Solid-State Chemistry", 3),
	("Radiochemistry", 3),
	("Astrochemistry", 3),
	("Green Chemistry", 4);

# Computer Science classes
INSERT INTO class(name, credits)
VALUES
	("Introduction to Computer Science", 3),
	("Data Structures and Algorithms", 3),
	("Object-Oriented Programming", 3),
	("Operating Systems", 3),
	("Computer Organization and Architecture", 4),
	("Database Systems", 3),
	("Artificial Intelligence", 4),
	("Computer Networks", 4),
	("Software Engineering", 4),
	("Computer Graphics", 4),
	("Human-Computer Interaction", 3),
	("Theory of Computation", 3),
	("Programming Languages", 3),
	("Web Development", 3),
	("Mobile Application Development", 3),
	("Distributed Systems", 3),
	("Computer Security", 3),
	("Cloud Computing", 3),
	("Machine Learning", 4),
	("Computer Vision", 3),
	("Robotics", 4), 
	("Computer Ethics", 4),
	("Data Science", 4),
	("Natural Language Processing", 4),
	("High-Performance Computing", 4);

#English Classes
INSERT INTO class (name, credits)
VALUES
	("Introduction to Literature",4),
	("Creative Writing",3),
	("Critical Theory and Practice",4),
	("Shakespeare",4),
	("American Literature",4),
	("British Literature",4),
	("Poetry",4),
	("Fiction Writing",4),
	("Drama",4),
	("The Novel",4),
	("Literary Criticism",4),
	("Modernism and Postmodernism",4),
	("Victorian Literature",4),
	("Romanticism",4),
	("Children's and Young Adult Literature",4),
	("World Literature",3),
	("Women's Literature",3),
	("Film and Literature",3),
	("Science Fiction and Fantasy",3),
	("Literary Journalism",4),
	("Creative Nonfiction",4),
	("Contemporary Literature",3),
	("African American Literature",3),
	("Postcolonial Literature",3),
	("Literature and the Environment",3);

#Mathematics Classes
INSERT INTO class (name, credits)
VALUES
	("Calculus I",4),
	("Calculus II",4),
	("Linear Algebra",4),
	("Discrete Mathematics",4),
	("Differential Equations",3),
	("Probability Theory",4),
	("Real Analysis",4),
	("Complex Analysis",3),
	("Abstract Algebra",3),
	("Topology",4),
	("Number Theory",4),
	("Geometry",3),
	("Numerical Analysis",3),
	("Combinatorics",3),
	("Graph Theory",3),
	("Mathematical Logic",3),
	("Algebraic Topology",3),
	("Functional Analysis",3),
	("Game Theory",4),
	("Partial Differential Equations",4),
	("Measure Theory",4),
	("Stochastic Processes",3),
	("Coding Theory",3),
	("Nonlinear Dynamics",3),
	("Mathematical Modeling",4);

#Physics Classes
INSERT INTO class (name, credits)
VALUES
	("Classical Mechanics",4),
	("Electromagnetism",4),
	("Quantum Mechanics",4),
	("Thermodynamics and Statistical Mechanics",3),
	("Optics",4),
	("Solid State Physics",3),
	("Nuclear and Particle Physics",3),
	("Astrophysics",3),
	("Special Relativity",3),
	("General Relativity",3),
	("Mathematical Methods for Physics",3),
	("Experimental Physics",3),
	("Computational Physics",3),
	("Biophysics",4),
	("Quantum Field Theory",4),
	("Condensed Matter Physics",3),
	("Plasma Physics",3),
	("Atomic and Molecular Physics",3),
	("Cosmology",3),
	("Quantum Optics",3),
	("Nonlinear Dynamics and Chaos",4),
	("Environmental Physics",4),
	("Quantum Information and Computing",4),
	("High Energy Physics",4),
	("Soft Matter Physics",4);
